### ISSUE TITLE
[Bug] TEXT NOT VISIBLE IN DARK MODE

### ISSUE THREAD

**Issue by KartikSaxena19** [Luson045/medi-connect#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description?

When the dark mode is apply the text in login and sinup page is not visible

### Add Screenshots

![Screenshot 2024-10-19 152754](https://github.com/user-attachments/assets/972ac0dc-42cd-4785-92be-5a1887edcd61)
![Screenshot 2024-10-19 152803](https://github.com/user-attachments/assets/46117b0f-6e83-4cd9-a390-1f5e03ad5707)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue (Optional)
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Trevisx07** [comment]
@KartikSaxena19 Aldready there was a issue and is solved now!

**Comment by KartikSaxena19** [comment]
![Screenshot_2024-10-19-19-57-58-730_com android chrome](https://github.com/user-attachments/assets/46307425-a22f-48ff-899a-b825e96d36cd)

Not visible yet

**Comment by Trevisx07** [comment]
@KartikSaxena19 Okay, its not visible for register function only. Do one thing make a new issue for this for register button only. Login one is fixed. 
![image](https://github.com/user-attachments/assets/af71b3d0-da44-4668-8bf2-5c7232c9d0e4)

You need to fix this:
![image](https://github.com/user-attachments/assets/b4949be4-43f9-48fd-9969-6762d87e3940)

Make a issue i will assign and make PR quickly so that i can merge it.
